# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Manejador_OATs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField()),
                ('noAlumnos', models.IntegerField()),
                ('alumnos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manejador_OATs.OAT')),
            ],
        ),
    ]
