# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OAT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('src_image', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='oats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manejador_OATs.OAT'),
        ),
    ]
